### PR TITLE
Query multiple tables

### PR DESCRIPTION
**Pull request by eamador1**
Since the last code review, the following was done in this project:
---

- create a tables named owners and species ✅
- modify animals table ✅
- insert new data into tables ✅
- modify columns in animals table ✅
- write queries (using JOIN) ✅

Queries screenshots:

What animals belong to Melody Pond?
image

List of all animals that are pokemon (their type is Pokemon)
image

List all owners and their animals, remember to include those that don't own any animal
image

How many animals are there per species?
image

List all Digimon owned by Jennifer Orwell
Jennifer Orwell-Digimon

List all animals owned by Dean Winchester that haven't tried to escape
owned-by-Dean Winchester-not escaped

Who owns the most animals?
who owns the most?

### CODE REVIEW

**Review by Davidosky007 — CHANGES_REQUESTED** [review]
Hi @eamador1 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* Multiple tables quiered 👍 
* Used primary key & foreign key mechanism for joining tables 👍 
* Good looking readme 👍 


## Required Changes ♻️
* As stated in the [requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_multiple_tables.md#:~:text=Take%20a%20screenshot,Pull%20Request%20description.) you are required to 

> Take a screenshot of the results of your queries.
> Remember to add the screenshot with the results of your queries to your Pull Request description.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Nemwel-Boniface — COMMENTED** [review]
# Hello @eamador1   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have received your second opinion request with a complaint about the previous reviewer @Davidosky007 . Below are my findings:

I have inspected the project and checked the requested changes and found that @Davidosky007  was correct to request you to add the screenshots of your query results in your pull request description. KIndly note that he was simply reviewing your project following the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_multiple_tables.md) that you had for this project.

image

While adding the screenshots in a folder is neat, note that for reviewing purposes, doing so would make your submission to not meet all the project requirements.

**What you should do:**

- [ ] KIndly as requested by @Davidosky007  add the screenshots of your query results to your pull request description. Simply click on the three dots at the top right of the PR description and select "edit"  to add the screenshots.
- [ ] To also make it easier for the reviewers to follow up, please add a note ontop of each screenshot letting the reviewer know that this screenshot is for this query.

In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

**Comment by eamador1** [comment]
@Davidosky007, @Nemwel-Boniface  Thank you. I needed that explanation on what I was exactly being asked to do, because I thought I had done it right👍🏼

**Comment by eamador1** [comment]
Since the last review, the follwing was done:
---

- Add screenshot fo queries to PR description

**Review by codepantha — APPROVED** [review]
# STATUS: APPROVED 🟢 ✔️ 

## Hi @eamador1 👋, 

Great job implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights 🎯 
✔️ Descriptive PR
✔️Multiple tables queried 📌 
✔️ Used primary key and foreign keys for joining tables 📌 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
